# Generated by Django 4.2.3 on 2023-07-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='img_url',
            field=models.CharField(default='https://media.istockphoto.com/id/1337144146/vector/default-avatar-profile-icon-vector.jpg?s=612x612&w=0&k=20&c=BIbFwuv7FxTWvh5S3vB6bkT0Qv8Vn8N5Ffseq84ClGI=', max_length=500),
        ),
    ]
