# Generated by Django 4.2.3 on 2023-07-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_contact_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='meta_des',
            field=models.CharField(default='Hello Sir, well reveal the outreach partner wala poster', max_length=99),
        ),
    ]
