# Generated by Django 4.2.3 on 2023-07-18 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_contact_meta_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 18)),
        ),
    ]
