# Generated by Django 4.2.3 on 2023-07-20 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(default='https://media.istockphoto.com/id/1337144146/vector/default-avatar-profile-icon-vector.jpg?s=612x612&w=0&k=20&c=BIbFwuv7FxTWvh5S3vB6bkT0Qv8Vn8N5Ffseq84ClGI=', max_length=500)),
                ('nam', models.CharField(default='Hazika', max_length=99)),
                ('orientation', models.CharField(max_length=99)),
                ('location', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=99)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 20)),
        ),
    ]
