# Generated by Django 4.2.3 on 2023-07-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_info_alter_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='rating',
            field=models.CharField(default=0.0, max_length=20),
        ),
    ]
