# Generated by Django 4.2.3 on 2023-07-31 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_city_country_field_profile_delete_info_city_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 31)),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default=None, max_length=99, unique=True),
        ),
    ]
